---
abstract: 'Stage-based conveyor-belt-like ticket handling system'
author:
  - 'Florian Helmberger C<< <fh@univie.ac.at> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Conveyor
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Null: 0
  Class::Scaffold: 0.08
  DBI: 0
  Data::Comparable: 0
  Data::Container: 0
  Data::Inherited: 0
  Data::Miscellany: 0
  Data::Storage: 0
  Date::Calc: 0
  Encode: 0
  Error::Hierarchy: 0
  HTTP::Date: 0
  HTTP::Engine: 0
  Hash::Flatten: 0
  Hook::Modular: 0
  IO::Pager: 0
  JSON::XS: 0
  Log::Dispatch: 0
  MIME::Types: 0
  Pod::PlainText: 0
  SOAP::Lite: 0
  String::CamelCase: 0
  String::FlexMatch: 0
  Term::Shell::Enhanced: 0
  Test::Differences: 0
  Test::More: 0
  Test::utf8: 0
  Text::Table: 0
  Time::HiRes: 0
  URI::Escape: 0
  YAML: 0
  YAML::Active: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
