--- 
abstract: ~
author: 
  - "{% ELSE %}"
build_requires: 
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Conveyor
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Null: 0
  Class::Scaffold: 0.03
  DBI: 0
  Data::Comparable: 0
  Data::Container: 0
  Data::Inherited: 0
  Data::Miscellany: 0
  Data::Storage: 0
  Date::Calc: 0
  Error::Hierarchy: 0
  Hash::Flatten: 0
  IO::Pager: 0
  Pod::PlainText: 0
  SOAP::Lite: 0
  String::FlexMatch: 0
  Term::Shell::Enhanced: 0
  Test::Differences: 0
  Test::More: 0
  Test::utf8: 0
  Text::Table: 0
  Time::HiRes: 0
  YAML: 0
  YAML::Active: 0
  perl: 5.6.0
version: 0.02
